import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { AtlasForge } from '../../src/core/facade.js';

describe('Memory proof and task-note promotion policy', () => {
    const testRoot = path.resolve('.test-memory-proof');

    beforeEach(() => {
        if (fs.existsSync(testRoot)) {
            fs.rmSync(testRoot, { recursive: true, force: true });
        }
    });

    afterEach(() => {
        if (fs.existsSync(testRoot)) {
            fs.rmSync(testRoot, { recursive: true, force: true });
        }
    });

    it('fails doctor when bugfix memory has no evidence', async () => {
        await AtlasForge.initWithReport(testRoot, 'codex');
        const forge = await AtlasForge.load(testRoot, 'codex');
        await forge.add({
            memory_type: 'bugfix',
            title: 'Fix race condition',
            summary: 'Patch lock ordering bug',
            what_changed: 'Adjusted lock order in scheduler path',
            why_it_matters: 'Prevents deadlock under load',
        });

        const doctor = await forge.doctor();
        expect(doctor.passed).toBe(false);
        expect(doctor.checks.some((check) => check.name === 'proof' && check.status === 'fail')).toBe(true);
    });

    it('does not require proof for workflow decisions', async () => {
        await AtlasForge.initWithReport(testRoot, 'codex');
        const forge = await AtlasForge.load(testRoot, 'codex');
        await forge.add({
            memory_type: 'decision',
            decision_class: 'workflow',
            title: 'Use Atlas close gate',
            summary: 'Always run doctor before close',
            what_changed: 'Standardized team process',
            why_it_matters: 'Reduces promotion regressions',
        });

        const doctor = await forge.doctor();
        expect(doctor.passed).toBe(true);
        expect(doctor.checks.some((check) => check.name === 'proof' && check.status === 'fail')).toBe(false);
    });

    it('does not auto-promote autogenerated task-note summary entries', async () => {
        await AtlasForge.initWithReport(testRoot, 'codex');
        const forge = await AtlasForge.load(testRoot, 'codex');
        await forge.taskStart({ summary: 'Close without durable memory' });

        const close = await forge.taskClose({ summary: 'No durable memory this cycle' });
        expect(close.promoted_entries.length).toBe(0);
        expect(close.skipped_entries.some((entry) => entry.memory_type === 'task-note')).toBe(true);

        const status = await forge.status('codex');
        expect(status.snapshot.staging_count).toBe(0);
        expect(status.snapshot.canonical_count).toBe(0);
    });

    it('keeps manual task-note entries in staging until explicitly retyped', async () => {
        await AtlasForge.initWithReport(testRoot, 'codex');
        const forge = await AtlasForge.load(testRoot, 'codex');
        await forge.taskStart({ summary: 'Manual task note retention' });
        await forge.add({
            memory_type: 'task-note',
            title: 'Investigate flaky endpoint',
            summary: 'Need deeper traces before durable memory',
            what_changed: 'Collected partial traces only',
            why_it_matters: 'Not enough certainty for canonical memory',
        });

        await forge.taskClose({ summary: 'Task note should remain staging' });
        const status = await forge.status('codex');
        expect(status.snapshot.staging_count).toBe(1);
    });
});
